# Generated by Django 5.0.4 on 2024-04-19 05:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user1', models.CharField(max_length=150, null=True, verbose_name='raqib 1')),
                ('user2', models.CharField(max_length=150, null=True, verbose_name='raqib 2')),
                ('result', models.PositiveIntegerField(null=True)),
                ('is_finished', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Match',
                'verbose_name_plural': 'Matchs',
                'db_table': 'match',
            },
        ),
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
            ],
            options={
                'verbose_name': 'Musobaqa',
                'verbose_name_plural': 'Musobaqalar',
                'db_table': 'competition',
                'indexes': [models.Index(fields=['title', 'is_active'], name='competition_title_5714ea_idx')],
            },
        ),
        migrations.CreateModel(
            name='MatchResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user1_point', models.CharField(max_length=500, null=True)),
                ('user2_point', models.CharField(max_length=500, null=True)),
                ('total_point1', models.PositiveIntegerField(null=True)),
                ('total_point2', models.PositiveIntegerField(null=True)),
                ('is_fineshed', models.BooleanField(default=False)),
                ('knock_out', models.CharField(choices=[(1, 'user1'), (2, 'user2')], max_length=10, null=True)),
                ('match', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.match')),
                ('referee', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='match_result', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'match_result',
                'verbose_name_plural': 'match_results',
                'db_table': 'match_result',
            },
        ),
        migrations.CreateModel(
            name='Ring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, null=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('competition', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ring', to='app.competition', verbose_name='Competition')),
            ],
            options={
                'verbose_name': 'Ring',
                'verbose_name_plural': 'Ringes',
                'db_table': 'ring',
            },
        ),
        migrations.AddField(
            model_name='match',
            name='ring',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.ring'),
        ),
        migrations.AddIndex(
            model_name='ring',
            index=models.Index(fields=['is_active'], name='ring_is_acti_724e22_idx'),
        ),
        migrations.AddIndex(
            model_name='ring',
            index=models.Index(fields=['competition'], name='ring_competi_acdbe8_idx'),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['is_finished'], name='match_is_fini_8290b1_idx'),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['ring'], name='match_ring_id_5ff28d_idx'),
        ),
    ]
