# Generated by Django 5.0.4 on 2024-04-18 08:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_alter_refereeuser_ring_alter_refereeuser_username'),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchresult',
            name='referee',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='match_result', to='account.refereeuser'),
        ),
    ]
