# Generated by Django 5.0.4 on 2024-04-18 09:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_matchresult_referee'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchresult',
            name='referee',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='match_result', to=settings.AUTH_USER_MODEL),
        ),
    ]
