# Generated by Django 5.0.4 on 2024-04-27 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_competition_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matchresult',
            old_name='is_fineshed',
            new_name='is_finished',
        ),
    ]
