# Generated by Django 5.0.4 on 2024-04-27 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_is_fineshed_matchresult_is_finished'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchresult',
            name='knock_out',
            field=models.CharField(blank=True, choices=[(1, 'user1'), (2, 'user2')], max_length=10, null=True),
        ),
    ]
