# Generated by Django 5.0.4 on 2024-04-18 10:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_ring_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
