# Generated by Django 5.0.4 on 2024-04-30 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_matchresult_total_point1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchresult',
            name='total_point1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='matchresult',
            name='total_point2',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
