# Generated by Django 5.0.4 on 2024-04-18 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_competition_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ring',
            name='user',
        ),
    ]
