# Generated by Django 5.0.4 on 2024-04-18 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_ring_user'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='matchresult',
            table='match_result',
        ),
    ]
