# Generated by Django 5.0.4 on 2024-04-17 08:41

import account.models
import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_refereeuser'),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refereeuser',
            name='password',
            field=models.PositiveBigIntegerField(validators=[account.models.password_validator]),
        ),
        migrations.AlterField(
            model_name='refereeuser',
            name='ring',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.ring', verbose_name='Ring'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, error_messages={'unique': 'User this phone number already exists.'}, help_text='Required. Only international format used. (+998901234567)', max_length=128, null=True, region=None, unique=True, verbose_name='Phone number'),
        ),
    ]
