# Generated by Django 5.0.4 on 2024-04-30 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_kotib',
        ),
    ]
