# Generated by Django 5.0.4 on 2024-04-17 09:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_refereeuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refereeuser',
            name='password',
            field=models.PositiveBigIntegerField(validators=[django.core.validators.RegexValidator(code='invalid_login', message='Enter a valid registration number in the format 1234567654', regex='^[1-9]+$')]),
        ),
        migrations.AlterField(
            model_name='refereeuser',
            name='username',
            field=models.CharField(max_length=100, null=True, validators=[django.core.validators.RegexValidator(code='invalid_login', message='Enter a valid registration number in the format 1234567654', regex='^[a-z]+$')]),
        ),
    ]
