# Generated by Django 5.0.4 on 2024-04-17 10:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_alter_refereeuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refereeuser',
            name='password',
            field=models.PositiveBigIntegerField(validators=[django.core.validators.RegexValidator(code='invalid_password', message='Enter a valid password in the format 1234567654', regex='^[1-9]+$')]),
        ),
        migrations.AlterField(
            model_name='refereeuser',
            name='username',
            field=models.CharField(default=1, max_length=100, validators=[django.core.validators.RegexValidator(code='invalid_username', message='Enter a valid username in the format sdfsf7654', regex='^[1-9 a-z]+$')]),
            preserve_default=False,
        ),
    ]
