# Generated by Django 5.0.4 on 2024-04-18 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_alter_user_password_alter_user_updated_at_and_more'),
        ('app', '0008_remove_ring_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ring',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.ring'),
        ),
    ]
