# Generated by Django 5.0.4 on 2024-04-18 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_user_ring'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_kotib',
            field=models.BooleanField(default=False),
        ),
    ]
