# Generated by Django 5.0.4 on 2024-04-18 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('press_service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is active'),
        ),
    ]
